# Testing github workflow. Nothing interesting should happen.

name: Lint, test, build, push

on:
  push:
    # any branch with no "/", i.e. a top-level branch
    branches: ['*']
  pull_request:
    branches: ['**']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: docker build
        uses: docker/build-push-action@v1
        with:
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
          # push...
          


