name: pusher
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./v6
          push: true
          tags: pastorrob/test-kernel-build:v6
            #      - name: Deploy to production
            #        uses: docker/metadata-action@v3
            #        with:
            #          images: pastorrob/test-kernel-build:v6
